services:
  frontend:
    build:
      context: .
      dockerfile: ./deploy/frontend.dockerfile
      args:
        # The release tag for the client build (by default the client uses `latest`).
        # - For a different build, supply the following param: `/play?r={VERSION}`.
        VERSION: "dev"
        # Mode must be either "release" (for production) or "watch" (for development)
        MODE: "release"
        # The URL that will be accessed by the user's browser
        # - When running in production, you likely want to use `wss://{YOUR_DOMAIN}/ws`
        SERVER_SOCKET_URL: "ws://0.0.0.0:8080/ws"
    volumes:
      - frontend:/build
    ports:
      # Port used for hot reloading in shadow-cljs's watch mode
      - "9630:9630"
    develop:
      watch:
        - action: sync
          path: ./src/main/ogres/app
          target: /build/src/main/ogres/app
        - action: rebuild
          path: package.json

  backend:
    build:
      context: .
      dockerfile: ./deploy/backend.dockerfile
    expose:
    # The websocket connection exposed by the server
    - "8090"

  nginx:
    build:
      context: .
      dockerfile: ./deploy/nginx.dockerfile
      args:
        VERSION: "dev"
        # The URL to the server's websocket, which will be proxied by nginx
        SERVER_SOCKET_URL: "http://backend:8090/ws"
    volumes:
        - ./deploy/docker-nginx.template:/etc/nginx/templates/default.conf.template:ro
        - frontend:/usr/share/nginx/app
    ports:
      - "8080:80"

volumes:
  frontend:
